### ISSUE TITLE
Change `${include(...)}` syntax

### ISSUE THREAD

**Issue by tleguijt** [labd/mach-composer#115]
Proposal from @mvantellingen in #114 to change the syntax

`${include(components.yml)}` to `${include("components.yml")}`

**Comment by edgehero** [comment]
Could also be ${file(../link_to_yaml)} if you follow other cloud frameworks examples

**Comment by tleguijt** [comment]
I will close this issue since there is not a direct need in changing this.
If there is a good reason to require quotes or change `include` into `file` then we can re-open this issue,
