### ISSUE TITLE
Add SOPS support for `${include(...)}` files

### ISSUE THREAD

**Issue by tleguijt** [labd/mach-composer#119]
At the moment, files that are included (with either `!include` or `${include(..)}`) are not automatically decrypted with SOPS.
Just as with variable files, it would be useful if MACH would detect encrypted included and decrypt them

**Comment by tleguijt** [comment]
Since we are now only supporting include for the components definitions, it won't make sense to add support for SOPS encryption for that.

@mvantellingen  @pimvernooij  shall we either support include in more places, or close this feature request?

**Comment by mvantellingen** [comment]
I don't think we will ever have secrets in a components file. If we do want to have them for custom plugins we could put the secrets in a variable file and reference them from the components block:

e.g.
```yaml
components:
 - name: my-component
   my-plugin:
       my-secret: ${var.my-secret}
```
