### ISSUE TITLE
Add template option to extend generated Terraform configuration

### ISSUE THREAD

**Issue by tleguijt** [labd/mach-composer#124]
This could be useful for example to add extra custom Terraform providers.

For example with an `terraform_extension_template: tf-tmpl.tf` option in the MACH config.

**Comment by BramKaashoek** [comment]
A direct use case.
For a component using Stripe as payment provider I need to include their provider: 

`terraform {
  required_providers {
    stripe = {
      source = "franckverrot/stripe"
      version = "1.8.0"
    }
  }
}
`

**Comment by tleguijt** [comment]
Also support variables (varfile and env) like so:

```hcl
terraform {
  required_providers {
    stripe = {
      source = "franckverrot/stripe"
      version = "1.8.0"

      username = ${var.provider.username}
      username = ${env.STRIPE_USERNAME}
    }
  }
}
```

**Comment by mvantellingen** [comment]
I think this can now be achieved via plugins.

Of course creating a plugin for only adding a provider seems overkill. But it's quite easy to create a reusable provider setting plugin (`mach-composer-plugin-add-providers`)

Agree to close?
