### ISSUE TITLE
Mach Update is broken if you use a variables file

### ISSUE THREAD

**Issue by korsvanloon** [labd/mach-composer#128]
If you are using a variables file, you cannot use Mach update anymore because it cannot validate the file.

```yml
$ mach update -f main.yml 
Parsing main.yml...
Error: Variable sentry.auth_token not found in variables
```

Because updating only concerns components, these validations are not necessary.
Removing these validations for mach update will also solve this ticket.

**Comment by tleguijt** [comment]
On which version did this occur?
This has been fixed since 1.1-b.3
