### ISSUE TITLE
mach bootstrap component - output structure and obsolete files

### ISSUE THREAD

**Issue by boro2g** [labd/mach-composer#134]
When running on windows machine, if you run `mach bootstrap component` and follow the wizard with defaults for most options (ie AWS/Node), using either PS or bash as the runner, the folder structure of the output is:
![image](https://user-images.githubusercontent.com/13680499/145191759-3963d928-f22c-41e7-b021-d82d95431a0f.png)

## Output structure
When you then run `yarn`, no `package.json` is found in the root as it exists in `__node__`. Is this by design? 
Are there manual, or automated steps that should run to clean the output folder to remove e.g. `__python__` and to move files out from `__node__`? Or should `yarn` be run within `__node__`?

## Obsolete files
Within the `__node__` folder, you have example code for listening to `extensions, http and subscriptions` - depending on the options selected via the wizard, could the unused ones be removed?

**Comment by tleguijt** [comment]
Hi @boro2g thanks for submitting the issue.
Can you share what environment you are running on? Which OS and what python version.

**Comment by tleguijt** [comment]
This most probably has to do with the following script which has not been tested on windows yet;
https://github.com/labd/mach-component-cookiecutter/blob/master/hooks/post_gen_project.py

**Comment by pimvernooij** [comment]
Other clients that use MACH composer on windows, have been using WSL to run it in - perhaps that is a solution for the time being?

https://docs.microsoft.com/en-us/windows/wsl/install

**Comment by boro2g** [comment]
> Hi @boro2g thanks for submitting the issue. Can you share what python version you are using?

Sure, its:
```
python
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
```

Let me try the WSL suggestions...

Thanks (Nick Hills, Valtech)

**Comment by pimvernooij** [comment]
Could you try upgrading to python 3.7+? That is the version that we test MACH composer against.

**Comment by boro2g** [comment]
Morning! I've upgraded to: `Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32` but still see the same incorrect folder structure as seen above ^. 

Are there any debug steps I can run as part of the `mach bootstrap component` wizard?

FYI via WSL it ran ok and cleaned up the folders as expected.

**Comment by tleguijt** [comment]
Hi @boro2g what you could do is download the python script https://github.com/labd/mach-component-cookiecutter/blob/master/hooks/post_gen_project.py and place it within one of your components folders (so next to the MANIFEST file).
And then run it manually. See if you see any errors in the output and otherwise use a debugger to see what's actually happening.

Go to hear that running this in WSL works as expected.

**Comment by boro2g** [comment]
Interestingly that script ran fine when I ran manually:
![image](https://user-images.githubusercontent.com/13680499/145805231-af646216-b4a9-42d3-ad0d-967302e8ad53.png)

FYI when running the `bootstrap` command, my ps prompt is running as admin

**Comment by tleguijt** [comment]
What could be is that windows has a problem with the hook being a symbolic link in the cookiecutter project.
For now, I've replaced the symlinks with the actual files. Could you try running the `mach bootstrap` command again?

**Comment by boro2g** [comment]
Works a treat now :)
