### ISSUE TITLE
Create AWS and Azure specific Docker containers

### ISSUE THREAD

**Issue by tleguijt** [labd/mach-composer#17]
At the moment, the MACH docker container contains all terraform providers and the Azure CLI.
To provide more light-weight containers we should create two extra flavours for both cloud integrations.

**Comment by mvantellingen** [comment]
We now generate a number of image flavours based on all, cloud-specific, terraform-specific.

See https://github.com/labd/mach-composer/pkgs/container/mach-composer/versions
