### ISSUE TITLE
Deploy docker-based microservices via Fargate (in AWS)

### ISSUE THREAD

**Issue by pimvernooij** [labd/mach-composer#38]
@mvantellingen showed how easy it is to deploy a Fargate based docker container, for use-cases where AWS Lambda is not sufficient.

I suggest we document it and add it as an example, so users can decide what platform to use, to deploy on. I'm not sure if any changes are required to MACH composer itself.

Perhaps document pro's/cons of using either and proper guidance when to use what (including how to combine both options in a single deployment).

**Comment by mvantellingen** [comment]
"moved" to https://github.com/mach-composer/mach-composer-plugin-aws/issues/3
