### ISSUE TITLE
Support cloudfront distribution in front of regional API gw

### ISSUE THREAD

**Issue by davidweterings** [labd/mach-composer#66]
API gateway v1 supports AWS creating a Cloudfront distribution which sits in front of the API gateway (Edge deployment). 

Since API Gateway v2 only supports regional endpoints, we would need to setup our own Cloudfront distribution in front to get effective global routing (one of the use cases is going from HK to AWS eu-west-1), but it seems like something that should be in MACH.

**Comment by mvantellingen** [comment]
"moved" to https://github.com/mach-composer/mach-composer-plugin-aws/issues/2
